---
title: "Long Covid study scRNA-seq, 24 month time point, data integration"
author: "Emily Kibbler"
date: "2025-08-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

This pipeline is for analysis of scRNA-seq data from a publicly available data set.

Citation: 

Phetsouphanh C, [...] Matthews GV. Improvement of immune dysregulation in individuals with long COVID at 24-months following SARS-CoV-2 infection. Nat Commun. 2024 Apr 17;15(1):3315. doi: 10.1038/s41467-024-47720-8. PMID: 38632311; PMCID: PMC11024141.


[Click here to access the data from GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE262861)

This script integrates the four libraries collected at 24 months.


```{r options, echo = FALSE, results = FALSE}
mem.maxVSize(Inf)
options(future.globals.maxSize = 32 * 1e9)
```

```{r load packages, results = FALSE}
library(Seurat)
library(ggpubr)
library(tidyverse)
```

```{r integrate}
# Read in integration anchors generated by the previous script
anchors <- readRDS( "./data/covid/int_anchors_24mths.rds")

combo <- IntegrateData(anchorset = anchors,
                                     normalization.method = "SCT")

# Export, to be used by future scripts
saveRDS(combo, "./data/covid/initial_combo_24mths.rds")

```
